spring:
  profiles:
    active: prod
    group:
      local: member-local
      dev: member-dev
      prod: member-prod

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    springframework:
      security: trace